import { useEffect, useMemo, useState } from 'react';
import { Check, Plus, RefreshCw, Save, Search, Trash2 } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../hooks/useAuth';
import { PageHeader } from '../components/PageHeader';
import { Badge } from '../components/Badge';
import { EmptyState } from '../components/EmptyState';
import { Modal } from '../components/Modal';

type ModuleKey='exams'|'results'|'fees'|'events'|'notifications'|'ptm'|'notices';
type Field={key:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[]};
const cfg:Record<ModuleKey,{title:string;subtitle:string;table:string;columns:string[];fields:Field[]}>={
 exams:{title:'Exams',subtitle:'Plan and publish school examinations.',table:'exams',columns:['name','exam_date','start_time','end_time','room'],fields:[{key:'name',label:'Exam name',required:true},{key:'class_id',label:'Class',type:'class',required:true},{key:'section_id',label:'Section',type:'section',required:true},{key:'subject_id',label:'Subject',type:'subject',required:true},{key:'exam_date',label:'Date',type:'date',required:true},{key:'start_time',label:'Start time',type:'time',required:true},{key:'end_time',label:'End time',type:'time',required:true},{key:'room',label:'Room'},{key:'notes',label:'Notes',type:'textarea'}]},
 results:{title:'Results',subtitle:'Enter and publish marks for authorized students.',table:'results',columns:['student','exam','subject','marks','max_marks','grade','published'],fields:[{key:'student_id',label:'Student',type:'student',required:true},{key:'exam_id',label:'Exam',type:'exam',required:true},{key:'subject_id',label:'Subject',type:'subject',required:true},{key:'marks',label:'Marks',type:'number',required:true},{key:'max_marks',label:'Maximum marks',type:'number',required:true},{key:'grade',label:'Grade'},{key:'comments',label:'Comments',type:'textarea'}]},
 fees:{title:'Fees',subtitle:'Track fee obligations and receipts. Payments are not processed here.',table:'fees',columns:['student','category','amount','due_date','status','receipt_ref'],fields:[{key:'student_id',label:'Student',type:'student',required:true},{key:'category',label:'Category',required:true},{key:'amount',label:'Amount',type:'number',required:true},{key:'due_date',label:'Due date',type:'date',required:true},{key:'status',label:'Status',type:'select',options:[{value:'PENDING',label:'Pending'},{value:'PAID',label:'Paid'},{value:'OVERDUE',label:'Overdue'}]},{key:'receipt_ref',label:'Receipt/reference'}]},
 events:{title:'Events',subtitle:'School events, competitions, functions and important dates.',table:'events',columns:['title','starts_at','ends_at','location'],fields:[{key:'title',label:'Title',required:true},{key:'description',label:'Description',type:'textarea'},{key:'starts_at',label:'Starts',type:'datetime-local',required:true},{key:'ends_at',label:'Ends',type:'datetime-local'},{key:'location',label:'Location'}]},
 notifications:{title:'Notifications',subtitle:'Your scoped notifications. Mark individual or all as read.',table:'notifications',columns:['title','body','is_read','created_at'],fields:[]},
 ptm:{title:'PTM',subtitle:'Schedule teacher-parent meetings without creating a Parent role.',table:'ptm',columns:['starts_at','ends_at','status','instructions'],fields:[{key:'class_id',label:'Class',type:'class',required:true},{key:'section_id',label:'Section',type:'section',required:true},{key:'teacher_id',label:'Teacher',type:'teacher',required:true},{key:'starts_at',label:'Starts',type:'datetime-local',required:true},{key:'ends_at',label:'Ends',type:'datetime-local',required:true},{key:'status',label:'Status',type:'select',options:[{value:'SCHEDULED',label:'Scheduled'},{value:'COMPLETED',label:'Completed'},{value:'CANCELLED',label:'Cancelled'}]},{key:'instructions',label:'Instructions',type:'textarea'}]},
 notices:{title:'Notices',subtitle:'Publish school-wide or targeted communication.',table:'notices',columns:['title','body','priority','publish_at','target_role'],fields:[{key:'title',label:'Title',required:true},{key:'body',label:'Description',type:'textarea',required:true},{key:'priority',label:'Priority',type:'select',options:[{value:'LOW',label:'Low'},{value:'NORMAL',label:'Normal'},{value:'HIGH',label:'High'},{value:'URGENT',label:'Urgent'}]},{key:'publish_at',label:'Publish at',type:'datetime-local'},{key:'target_role',label:'Target role',type:'select',options:[{value:'',label:'Everyone'},{value:'STUDENT',label:'Students'},{value:'TEACHER',label:'Teachers'},{value:'ADMIN',label:'Admins'}]}]}
};

const label=(x:string)=>x.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function GenericModule({kind}:{kind:ModuleKey}){
 const c=cfg[kind]; const {profile}=useAuth(); const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [classes,setClasses]=useState<any[]>([]),[sections,setSections]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[exams,setExams]=useState<any[]>([]); const [form,setForm]=useState<Record<string,string>>({status:'PENDING',priority:'NORMAL'});

 const loadRefs=async()=>{const [a,b,d,e,f]=await Promise.all([supabase.from('classes').select('*').order('name'),supabase.from('sections').select('*').order('name'),supabase.from('subjects').select('*').order('name'),supabase.from('student_profiles').select('id,admission_no,profiles(full_name)').order('admission_no'),supabase.from('teacher_profiles').select('id,employee_no,profiles(full_name)').order('employee_no')]);setClasses(a.data??[]);setSections(b.data??[]);setSubjects(d.data??[]);setStudents(e.data??[]);setTeachers(f.data??[]);if(kind==='results'||kind==='ptm'){const {data}=await supabase.from('exams').select('id,name,exam_date').order('exam_date',{ascending:false});setExams(data??[])} };

 const load=async()=>{setLoading(true);setError('');try{let q:any=supabase.from(c.table).select('*').order('created_at',{ascending:false}).limit(200);if(kind==='exams')q=supabase.from(c.table).select('*,subjects(name),classes(name),sections(name)').order('exam_date',{ascending:true});if(kind==='results')q=supabase.from(c.table).select('*,student_profiles(admission_no,profiles(full_name)),exams(name),subjects(name)').order('created_at',{ascending:false});if(kind==='fees')q=supabase.from(c.table).select('*,student_profiles(admission_no,profiles(full_name))').order('due_date',{ascending:true});if(kind==='ptm')q=supabase.from(c.table).select('*,classes(name),sections(name),teacher_profiles(employee_no,profiles(full_name))').order('starts_at',{ascending:true});const {data,error}=await q;if(error)throw error;setRows(data??[]);if(c.fields.length)await loadRefs()}catch(e){setError(e instanceof Error?e.message:'Could not load records.')}finally{setLoading(false)}};

 useEffect(()=>{load()},[kind]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const canCreate=!!profile&&((profile.role==='ADMIN')||((profile.role==='TEACHER')&&['results','notices','ptm'].includes(kind))||(profile.role==='STUDENT'&&false));
 const canDelete=profile?.role==='ADMIN'&&(kind!=='notifications');

 const display=(r:any,k:string)=>{if(k==='student')return r.student_profiles?.profiles?.full_name??r.student_profiles?.admission_no??'—';if(k==='exam')return r.exams?.name??'—';if(k==='subject')return r.subjects?.name??'—';if(k==='class')return r.classes?.name??'—';if(k==='section')return r.sections?.name??'—';if(k==='teacher')return r.teacher_profiles?.profiles?.full_name??r.teacher_profiles?.employee_no??'—';const v=r[k];if(v===null||v===undefined||v==='')return '—';if(k==='published'||k==='is_read')return v?'Yes':'No';if(k.endsWith('_date')||k.endsWith('_at'))return new Date(v).toLocaleString();return String(v).slice(0,100)};

 const save=async()=>{if(!profile)return;setBusy(true);setError('');try{const payload:any={...form,school_id:profile.school_id};if(kind==='notices')payload.author_id=profile.id;if(kind==='results'&&payload.grade==='')delete payload.grade;if(kind==='results'&&payload.comments==='')delete payload.comments;Object.keys(payload).forEach(k=>payload[k]===''?delete payload[k]:null);const {error}=await supabase.from(c.table).insert(payload);if(error)throw error;setOpen(false);setForm({status:'PENDING',priority:'NORMAL'});await load()}catch(e){setError(e instanceof Error?e.message:'Save failed.')}finally{setBusy(false)}};

 const remove=async(id:string)=>{if(!confirm('Delete this record?'))return;const {error}=await supabase.from(c.table).delete().eq('id',id);if(error)setError(error.message);else await load()};
 const markRead=async(id?:string)=>{const q=id?supabase.from('notifications').update({is_read:true}).eq('id',id):supabase.from('notifications').update({is_read:true}).eq('is_read',false);const {error}=await q;if(error)setError(error.message);else await load()};
 const fieldOptions=(f:Field)=>{if(f.type==='class')return classes.map(x=>({value:x.id,label:x.name}));if(f.type==='section')return sections.filter(x=>!form.class_id||x.class_id===form.class_id).map(x=>({value:x.id,label:x.name}));if(f.type==='subject')return subjects.map(x=>({value:x.id,label:x.name}));if(f.type==='student')return students.map(x=>({value:x.id,label:`${x.profiles?.full_name??'Student'} · ${x.admission_no}`}));if(f.type==='teacher')return teachers.map(x=>({value:x.id,label:`${x.profiles?.full_name??'Teacher'} · ${x.employee_no}`}));if(f.type==='exam')return exams.map(x=>({value:x.id,label:`${x.name} · ${x.exam_date}`}));return f.options??[]};

 return <><PageHeader title={c.title} subtitle={c.subtitle} action={canCreate?<button className="primary small" onClick={()=>setOpen(true)}><Plus size={16}/>New</button>:undefined}/>{error&&<div className="form-error page-error">{error}</div>}<div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>{kind==='notifications'&&<button className="secondary" onClick={()=>markRead()}>Mark all read</button>}</div><div className="panel table-panel">{loading?<div className="skeleton-table">{[1,2,3,4,5].map(i=><i key={i}/>)}</div>:filtered.length?<div className="table-wrap"><table><thead><tr>{c.columns.map(k=><th key={k}>{label(k)}</th>)}<th/></tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{c.columns.map(k=><td key={k}>{k==='status'||k==='priority'?<Badge tone={String(r[k]).includes('APP')||r[k]==='PAID'||r[k]==='SCHEDULED'?'green':String(r[k]).includes('REJ')||r[k]==='OVERDUE'||r[k]==='CANCELLED'?'red':'blue'}>{label(String(r[k]??'—'))}</Badge>:<span>{display(r,k)}</span>}</td>)}<td>{kind==='notifications'&&!r.is_read?<button className="icon-btn" title="Mark read" onClick={()=>markRead(r.id)}><Check size={16}/></button>:null}{canDelete?<button className="icon-btn danger" title="Delete" onClick={()=>remove(r.id)}><Trash2 size={16}/></button>:null}</td></tr>)}</tbody></table></div>:<EmptyState title="No records found" text="Create a record or adjust your search."/>}</div>
 <Modal open={open} title={`Create ${c.title}`} onClose={()=>setOpen(false)}><div className="form-grid">{c.fields.map(f=>{const opts=fieldOptions(f);return <label key={f.key}>{f.label}{f.type==='textarea'?<textarea rows={4} value={form[f.key]??''} required={f.required} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:f.type==='select'||['class','section','subject','student','teacher','exam'].includes(f.type??'')?<select value={form[f.key]??''} required={f.required} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">Select {f.label.toLowerCase()}</option>{opts.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={f.type??'text'} value={form[f.key]??''} required={f.required} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>})}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" onClick={save} disabled={busy}><Save size={16}/>{busy?'Saving…':'Save'}</button></div></Modal></>;
}
