import { FormEvent, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { LockKeyhole, Phone, School as SchoolIcon, ShieldCheck } from 'lucide-react';
import { Logo } from '../components/Logo';
import { useAuth } from '../hooks/useAuth';

export default function Login(){const {signIn,configured}=useAuth();const nav=useNavigate();const [school,setSchool]=useState('');const [phone,setPhone]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [err,setErr]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setErr('');try{await signIn(school,phone,password);nav('/')}catch(e){setErr(e instanceof Error?e.message:'Login failed. Check your details.')}finally{setBusy(false)}};
 return <div className="auth-page"><div className="auth-art"><div className="art-glow one"/><div className="art-glow two"/><Logo/><div className="hero-copy"><span className="eyebrow">SAFE · SIMPLE · SMART</span><h1>One connected platform for every school.</h1><p>Attendance, academics, communication and school operations — designed around the real daily workflow.</p><div className="trust"><ShieldCheck/> Secure multi-school architecture</div></div></div><div className="auth-card-wrap"><form className="auth-card" onSubmit={submit}><Logo/><h2>Welcome back</h2><p>Sign in to your EduConnect school account.</p><label>School Code<div className="field"><SchoolIcon/><input value={school} onChange={e=>setSchool(e.target.value)} placeholder="EDU001" required/></div></label><label>Phone Number<div className="field"><Phone/><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="9876543210" required/></div></label><label>Password<div className="field"><LockKeyhole/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password" required/></div></label>{err&&<div className="form-error">{err}</div>}{!configured&&<div className="setup-note"><b>Supabase is not configured.</b><span>Add the values from <code>.env.example</code> to enable real authentication.</span></div>}<button className="primary full" disabled={busy||!configured}>{busy?'Signing in…':'Sign in securely'}</button><small className="auth-foot">Exactly three roles: Student · Teacher · Admin</small></form></div></div>}
